In [1]:
import numpy as np
import pandas as pd
data=pd.read_csv('play.csv')

C:\Users\TANUSHREE\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [3]:
data.drop(columns=['day'],inplace=True)

In [4]:
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [5]:
#problem 1
#outlook=sunny	temp=hot	humidity=high	wind=weak
#play or no play

In [6]:
# solution
#p(yes|sunny ,hot,high,weak)=p(yes|sunny)*p(yes|hot)*p(yes|high)*p(yes|weak)*p(yes)

#p(no|sunny ,hot,high,weak)=p(no|sunny)*p(no|hot)*p(no|high)*p(no|weak)*p(no)

#comapre and decide using posteriori rule

In [7]:
#problem 2
#outlook=overcast	temp=cold	humidity=low	wind=weak
#play or no play

In [8]:
# solution
#p(yes|overcast ,cold,low,weak)=p(yes|overcast)*p(yes|cold)*p(yes|low)*p(yes|weak)*p(yes)

#p(no|overcast ,cold,low,weak)=p(no|overcast)*p(no|cold)*p(no|low)*p(no|weak)*p(no)

#comapre and decide using posteriori rule

In [9]:
#steps
# training 
# lookup table
# testing

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
# WE want PROBABLITY OF YES AND NO
# p(yes)
# p(no)
py=9/(9+5)
pn=5/14

In [12]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [13]:
#problrm 1
#outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [15]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
pcoolno=1/5
photno=2/5
pmildno=2/5

pcoolyes=3/9
photyes=2/9
pmildyes=4/9

In [17]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [18]:
phighno=4/5
pnoemalno=1/5

phighyes=3/9
pnoemalyes=6/9

In [19]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [20]:
pstrongno=3/5
pweakno=2/5

pstrongyes=3/9
pweakyes=6/9

In [21]:
#outlook=sunny	temp=hot	humidity=high	wind=weak
#p(yes|sunny ,hot,high,weak)=p(yes|sunny)*p(yes|hot)*p(yes|high)*p(yes|weak)*p(yes)

#p(no|sunny ,hot,high,weak)=p(no|sunny)*p(no|hot)*p(no|high)*p(no|weak)*p(no)

In [22]:
pyes=py*psy*photyes*phighyes*pweakyes
pno=pn*psn*photno*phighno*pweakno

In [23]:
print(pyes)
print(pno)

0.007054673721340388
0.02742857142857143

In [24]:
# final answer is no

In [ ]:
!git add .

In [ ]:
!git commit -m "my work"

In [ ]:
!git push origin main